# Generated by Django 5.2.1 on 2025-06-04 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0002_alter_post_id_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]

